/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/AppProvider.vue')['default']
    BetterScroll: typeof import('./../components/custom/BetterScroll.vue')['default']
    ButtonIcon: typeof import('./../components/custom/ButtonIcon.vue')['default']
    CountTo: typeof import('./../components/custom/CountTo.vue')['default']
    CustomIconSelect: typeof import('./../components/custom/CustomIconSelect.vue')['default']
    DarkModeContainer: typeof import('./../components/common/DarkModeContainer.vue')['default']
    ExceptionBase: typeof import('./../components/common/ExceptionBase.vue')['default']
    FullScreen: typeof import('./../components/common/FullScreen.vue')['default']
    GithubLink: typeof import('./../components/custom/GithubLink.vue')['default']
    IconTooltip: typeof import('./../components/common/IconTooltip.vue')['default']
    LangSwitch: typeof import('./../components/common/LangSwitch.vue')['default']
    LookForward: typeof import('./../components/custom/LookForward.vue')['default']
    MenuToggler: typeof import('./../components/common/MenuToggler.vue')['default']
    PinToggler: typeof import('./../components/common/PinToggler.vue')['default']
    ReloadButton: typeof import('./../components/common/ReloadButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoybeanAvatar: typeof import('./../components/custom/SoybeanAvatar.vue')['default']
    SvgIcon: typeof import('./../components/custom/SvgIcon.vue')['default']
    SystemLogo: typeof import('./../components/common/SystemLogo.vue')['default']
    TableColumnSetting: typeof import('./../components/advanced/TableColumnSetting.vue')['default']
    TableHeaderOperation: typeof import('./../components/advanced/TableHeaderOperation.vue')['default']
    ThemeSchemaSwitch: typeof import('./../components/common/ThemeSchemaSwitch.vue')['default']
    WaveBg: typeof import('./../components/custom/WaveBg.vue')['default']
    WebSiteLink: typeof import('./../components/custom/WebSiteLink.vue')['default']
  }
}

// For TSX support
declare global {
  const AppProvider: typeof import('./../components/common/AppProvider.vue')['default']
  const BetterScroll: typeof import('./../components/custom/BetterScroll.vue')['default']
  const ButtonIcon: typeof import('./../components/custom/ButtonIcon.vue')['default']
  const CountTo: typeof import('./../components/custom/CountTo.vue')['default']
  const CustomIconSelect: typeof import('./../components/custom/CustomIconSelect.vue')['default']
  const DarkModeContainer: typeof import('./../components/common/DarkModeContainer.vue')['default']
  const ExceptionBase: typeof import('./../components/common/ExceptionBase.vue')['default']
  const FullScreen: typeof import('./../components/common/FullScreen.vue')['default']
  const GithubLink: typeof import('./../components/custom/GithubLink.vue')['default']
  const IconTooltip: typeof import('./../components/common/IconTooltip.vue')['default']
  const LangSwitch: typeof import('./../components/common/LangSwitch.vue')['default']
  const LookForward: typeof import('./../components/custom/LookForward.vue')['default']
  const MenuToggler: typeof import('./../components/common/MenuToggler.vue')['default']
  const PinToggler: typeof import('./../components/common/PinToggler.vue')['default']
  const ReloadButton: typeof import('./../components/common/ReloadButton.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SoybeanAvatar: typeof import('./../components/custom/SoybeanAvatar.vue')['default']
  const SvgIcon: typeof import('./../components/custom/SvgIcon.vue')['default']
  const SystemLogo: typeof import('./../components/common/SystemLogo.vue')['default']
  const TableColumnSetting: typeof import('./../components/advanced/TableColumnSetting.vue')['default']
  const TableHeaderOperation: typeof import('./../components/advanced/TableHeaderOperation.vue')['default']
  const ThemeSchemaSwitch: typeof import('./../components/common/ThemeSchemaSwitch.vue')['default']
  const WaveBg: typeof import('./../components/custom/WaveBg.vue')['default']
  const WebSiteLink: typeof import('./../components/custom/WebSiteLink.vue')['default']
}